In [33]:
import os
import bisect
from retry.api import retry_call
from python.git_operate import get_repo
from tqdm.auto import tqdm
import pandas as pd


URL_TEMPLATE = "https://github.com/{name_with_owner}/commit/{commit}"


top_dir = os.path.join(os.path.abspath(""))
res_dir = os.path.join(top_dir, "results")
data_dir = os.path.join(res_dir, "data")
owners_path = os.path.join(res_dir, "{language}")
names_path = os.path.join(res_dir, "{language}/{owner}")
pkl_path = os.path.join(res_dir, "{language}/{name_with_owner}.pkl")


def __RQ4(language: str) -> pd.DataFrame:
    rq3_dir = os.path.join(res_dir, f"rq3/{language}")

    all_df = pd.DataFrame()

    csv_paths = list(filter(lambda x: x.endswith(".csv"), os.listdir(rq3_dir)))
    csv_paths.sort()

    for csv_path in csv_paths:
        csv_df = pd.read_csv(os.path.join(rq3_dir, csv_path))

        name_with_owner = csv_path.replace(".csv", "")

        java_res_df = pd.read_pickle(
            os.path.join(
                top_dir,
                f"results/{language}",
                f"{name_with_owner.replace('_', '/', 1)}.pkl",
            )
        )

        java_res_df = java_res_df.map(lambda x: x if x else -1)

        java_res_df = java_res_df.astype(
            {
                "src start pos": "int",
                "src end pos": "int",
                "dst start pos": "int",
                "dst end pos": "int",
            }
        )

        java_res_df.to_pickle(
            os.path.join(
                top_dir,
                f"results/{language}",
                f"{name_with_owner.replace('_', '/', 1)}.pkl",
            )
        )

        merged_df = (
            csv_df.merge(
                java_res_df[
                    [
                        "commit",
                        "dst file",
                        "src file",
                        "src start pos",
                        "src end pos",
                        "dst start pos",
                        "dst end pos",
                    ]
                ],
                left_on=[
                    "insert commit",
                    "insert dst file",
                    "insert dst start pos",
                    "insert dst end pos",
                ],
                right_on=["commit", "dst file", "dst start pos", "dst end pos"],
                how="inner",
            )
            .drop(columns=["commit", "dst file", "dst start pos", "dst end pos"])
            .rename(
                columns={
                    "src file": "insert src file",
                    "src start pos": "insert src start pos",
                    "src end pos": "insert src end pos",
                }
            )
        )

        merged_df = (
            merged_df.merge(
                java_res_df[
                    [
                        "commit",
                        "dst file",
                        "src file",
                        "src start pos",
                        "src end pos",
                        "dst start pos",
                        "dst end pos",
                    ]
                ],
                left_on=[
                    "delete commit",
                    "delete src file",
                    "delete src start pos",
                    "delete src end pos",
                ],
                right_on=[
                    "commit",
                    "src file",
                    "src start pos",
                    "src end pos",
                ],
                how="inner",
            )
            .drop(
                columns=[
                    "commit",
                    "src file",
                    "src start pos",
                    "src end pos",
                ]
            )
            .rename(
                columns={
                    "dst file": "delete dst file",
                }
            )
        )

        merged_df["name_with_owner"] = name_with_owner

        all_df = pd.concat([all_df, merged_df])

    all_df = all_df.reindex(
        columns=[
            "name_with_owner",
            "insert commit",
            "insert src file",
            "insert src start pos",
            "insert src end pos",
            "insert dst file",
            "insert dst start pos",
            "insert dst end pos",
            "delete commit",
            "delete src file",
            "delete src start pos",
            "delete src end pos",
            "delete dst file",
        ],
    )
    all_df.reset_index(inplace=True, drop=True)

    return all_df


def calculate_line_offsets(source_code: str) -> list[int]:
    """
    Calculates the start offsets for each line in the source code.

    Args:
        source_code (str): The full source code as a string.

    Returns:
        list[int]: A list of line start offsets.
    """
    offsets = [0]
    current_offset = 0

    for line in source_code.splitlines(keepends=True):
        current_offset += len(line)
        offsets.append(current_offset)

    return offsets


def position_for(offset: int, source_code: str) -> tuple[int, int]:
    """
    Converts an offset into a (line, column) position based on the source code.

    Args:
        offset (int): The offset in the source code string.
        source_code (str): The full source code as a string.

    Returns:
        tuple: (line, column), both starting from 1.
    """
    lines = calculate_line_offsets(source_code)
    line = bisect.bisect_right(lines, offset) - 1
    column = offset - lines[line] + 1

    return line + 1, column


def removeNonAscii(s):
    return "".join(c for c in s if ord(c) < 128 and c != "\r")


extensions = {
    "java": "java",
    "javascript": "js",
    "ruby": "rb",
    "php": "php",
    "cpp": "cpp",
    "csharp": "cs",
}


def rq4(language: str):
    extension = extensions[language]

    rq4_df = __RQ4(language)
    rq4_df = rq4_df[268:]

    res_df = pd.DataFrame()

    for i, row in tqdm(rq4_df.iterrows(), total=len(rq4_df)):
        name_with_owner = row["name_with_owner"]
        insert_commit = row["insert commit"]
        insert_src_file = row["insert src file"]
        insert_dst_file = row["insert dst file"]
        insert_src_start_pos = row["insert src start pos"]
        insert_src_end_pos = row["insert src end pos"]
        insert_dst_start_pos = row["insert dst start pos"]
        insert_dst_end_pos = row["insert dst end pos"]
        delete_commit = row["delete commit"]
        delete_src_file = row["delete src file"]
        delete_src_start_pos = row["delete src start pos"]
        delete_src_end_pos = row["delete src end pos"]
        delete_dst_file = row["delete dst file"]

        assert insert_dst_file == delete_src_file

        repo = get_repo(top_dir, name_with_owner.replace("_", "/", 1), language)

        insert_src_file_content = removeNonAscii(
            retry_call(
                repo.git.show,
                fargs=[f"{insert_commit}^:{insert_src_file}"],
                tries=5,
                delay=1,
            )
        )
        insert_src_file_path = os.path.join(
            top_dir, f"rq4/{language}/{i}_insert_src.{extension}"
        )

        insert_dst_file_content = removeNonAscii(
            retry_call(
                repo.git.show,
                fargs=[f"{insert_commit}:{insert_dst_file}"],
                tries=5,
                delay=1,
            )
        )
        insert_dst_file_path = os.path.join(
            top_dir, f"rq4/{language}/{i}_insert_dst.{extension}"
        )

        if (
            name_with_owner == "signumsoftware_framework"
            and insert_commit == "058f6bf4968cfb578ba5b41f6b1e9bc1b07f5341"
        ):
            print(
                len(
                    retry_call(
                        repo.git.show,
                        fargs=[f"{insert_commit}:{insert_dst_file}"],
                        tries=5,
                        delay=1,
                    )
                ),
                len(insert_dst_file_content),
            )
            return insert_dst_file_content

        delete_src_file_content = removeNonAscii(
            retry_call(
                repo.git.show,
                fargs=[f"{delete_commit}^:{delete_src_file}"],
                tries=5,
                delay=1,
            )
        )
        delete_src_file_path = os.path.join(
            top_dir, f"rq4/{language}/{i}_delete_src.{extension}"
        )

        delete_dst_file_content = removeNonAscii(
            retry_call(
                repo.git.show,
                fargs=[f"{delete_commit}:{delete_dst_file}"],
                tries=5,
                delay=1,
            )
        )
        delete_dst_file_path = os.path.join(
            top_dir, f"rq4/{language}/{i}_delete_dst.{extension}"
        )

        row.loc["insert url"] = URL_TEMPLATE.format(
            name_with_owner=name_with_owner.replace("_", "/", 1), commit=insert_commit
        )
        row.loc["delete url"] = URL_TEMPLATE.format(
            name_with_owner=name_with_owner.replace("_", "/", 1), commit=delete_commit
        )
        row.loc["insert src file content"] = insert_src_file_content[
            insert_src_start_pos:insert_src_end_pos
        ]
        row.loc["insert dst file content"] = insert_dst_file_content[
            insert_dst_start_pos:insert_dst_end_pos
        ]
        row.loc["delete src file content"] = delete_src_file_content[
            delete_src_start_pos:delete_src_end_pos
        ]
        row.loc["insert src start rc"] = position_for(
            insert_src_start_pos, insert_src_file_content
        )
        row.loc["insert dst start rc"] = position_for(
            insert_dst_start_pos, insert_dst_file_content
        )
        row.loc["delete src start rc"] = position_for(
            delete_src_start_pos, delete_src_file_content
        )

        insert_commit = repo.commit(insert_commit)
        row.loc["replacement_msg"] = insert_commit.message

        delete_commit = repo.commit(delete_commit)
        row.loc["delete_msg"] = delete_commit.message

        res_df = pd.concat([res_df, row.to_frame().T])

    res_df["coding"] = None
    res_df = res_df.reindex(
        columns=[
            "name_with_owner",
            "insert url",
            "delete url",
            "replacement_msg",
            "delete_msg",
            "coding",
            "insert commit",
            "insert src file",
            "insert src start pos",
            "insert src start rc",
            "insert dst file",
            "insert dst start pos",
            "insert dst start rc",
            "delete commit",
            "delete src file",
            "delete src start pos",
            "delete dst file",
            "delete dst start pos",
            "delete dst start rc",
            "insert src file content",
            "insert dst file content",
            "delete src file content",
        ],
    )

    res_df = res_df.sample(frac=1, random_state=0)
    res_df = res_df.reset_index(drop=True)

    res_df.to_csv(os.path.join(res_dir, f"rq4/{language}_shuffle2.csv"))

    return res_df

In [34]:
df = rq4("csharp")

  0%|          | 0/57 [00:00<?, ?it/s]

11583 11299

In [36]:
print(len(df))

11299

In [16]:
pd.set_option("display.max_columns", None)

df

,name_with_owner,insert url,delete url,replacement_msg,delete_msg,coding,insert commit,insert src file,insert src start pos,insert src start rc,insert dst file,insert dst start pos,insert dst start rc,delete commit,delete src file,delete src start pos,delete dst file,delete dst start pos,delete dst start rc,insert src file content,insert dst file content,delete src file content
0,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,elefantes\n\n(TFS CS 5989)\n,Chequinazo entitygroups\n\n(TFS CS 6663)\n,None,fe7d3ff8826e4f2dfae0a3085882f37f3d990d5c,Signum.Engine.Extensions/Authorization/EntityG...,4187,"(113, 7)",Signum.Engine.Extensions/Authorization/EntityG...,4182,"(115, 3)",eb1b533826ad0b786fe883bdabdda8823e246a1b,Signum.Engine.Extensions/Authorization/EntityG...,5317,Signum.Engine.Extensions/Authorization/EntityG...,NaN,NaN,if (!saveDisabled && args.WasModified)\r...,if (!saveDisabled && ident.Modified)...,aveOptions.Destiny))\r\n {\r\n ...
1,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,None,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,3841,"(98, 13)",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,4139,"(101, 13)",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,4747,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,NaN,BusinessFlowStartTask(businessFlow);,Task.Run(() => BusinessFlowStartTask(businessF...,() => BusinessFlowStartTask(businessFlow)
2,AutoMapper_AutoMapper,https://github.com/AutoMapper/AutoMapper/commi...,https://github.com/AutoMapper/AutoMapper/commi...,Array mapping simplified quite a bit\n,"Instead of using ToArray, which double maps. F...",None,d8ea3389e0104fad7787964e369a1973697a0445,src/AutoMapper/Mappers/ArrayMapper.cs,1927,"(46, 11)",src/AutoMapper/Mappers/ArrayMapper.cs,1043,"(29, 13)",fb68f979b31f4875d636d18d0e6f6dbd6c74fc7b,src/AutoMapper/Mappers/ArrayMapper.cs,709,src/AutoMapper/Mappers/ArrayMapper.cs,NaN,NaN,return array as TDestinatio,return source.Cast<TSourceElement>()\n ...,"item => newItemFunc(item, itemContext)"
3,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,None,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,3273,"(84, 13)",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,3555,"(87, 13)",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,4163,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,NaN,RunnerRunEndTask(gingerRunner);,Task.Run(() => RunnerRunEndTask(gingerRunner));,() => RunnerRunEndTask(gingerRunner)
4,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,TryToken and QueryTokenDN builder with error m...,SubTokens(canAggregate)\n,None,058f6bf4968cfb578ba5b41f6b1e9bc1b07f5341,Signum.Web.Extensions/Chart/ChartClient.cs,9371,"(220, 68)",Signum.Web.Extensions/Chart/ChartClient.cs,8210,"(199, 92)",9880339ef979a380e89089dacaab00ec86c3c093,Signum.Web.Extensions/Chart/ChartClient.cs,8356,Signum.Web.Extensions/Chart/ChartClient.cs,NaN,NaN,o(\r\n,"chartToken, IChartBase chart, QueryDescription...",{\r\n bool canAggregate = (c...
5,rsdn_CodeJam,https://github.com/rsdn/CodeJam/commit/589249f...,https://github.com/rsdn/CodeJam/commit/82bf950...,Operator templates: comparison operators\n,Cleanup\n,None,589249fd5376b80b5ce93518ddf4f015e1537303,Main/src/Arithmetic/Operators.cs,508,"(21, 3)",Main/src/Arithmetic/Operators.cs,560,"(21, 3)",82bf9506fe7e1b8c4587b048c9762888cc8210d3,Main/src/Arithmetic/Operators.cs,646,Main/src/Arithmetic/Operators.cs,NaN,NaN,"public static readonly Func<T, T, int> Compare...","private static readonly Lazy<Func<T, T, int>> ...",() => Comparison<T>()
6,RomSunZ_StockSharp,https://github.com/RomSunZ/StockSharp/commit/4...,https://github.com/RomSunZ/StockSharp/commit/d...,FIX connector. Client side no longer use Quick...,FixServer. No longer use QuickFix.\n,None,49e74fe59b234e164dfb35ffae702aa359a17519,Connectors/Quik/Lua/LuaFixTransactionMessageAd...,4209,"(108, 6)",Connectors/Quik/Lua/LuaFixTransactionMessageAd...,4828,"(172, 6)",dadfd5b0efa28a36665a8904be4dfd172b767f53,Connectors/Quik/Lua/LuaFixTransactionMessageAd...,1776,Connectors/Quik/Lua/LuaFixTransactionMessageAd...,NaN,NaN,var condition = new QuikOrderCondition\n\t\t\t...,var executions = reader.ReadExecutionMessage(S...,tag =>\n\t\t\t\t\t{\n\t\t\t\t\t\tswitch ((Quik...
7,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,dqm.RegisterQuery\n,remove FileRepositoryEntity and add FileTypeAl...,None,d5e0bd110c5688280b0ba8565b271f63014e1b4c,Signum.Engine.Extensions/Files/FilePathLogic.cs,1719,"(48, 104)",Signum.Engine.Extensions/Files/FilePathLogic.cs,1719,"(48, 104)",40118cf0ba313e0aaeefb8a7f4a8478a40cc81bc,Signum.Engine.Extensions/Files/FilePathLogic.cs,3901,Signum.Engine.Extensions/Files/FilePathLogic.cs,NaN,NaN,lePathLogic_PreUnsafeDelete);\r\n\r\n ...,lePathLogic_PreUnsafeDelete);\r\n\r\n ...,ave<FilePathEntity>(false);\r\n\r\n ...
8,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,None,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,7812,"(187, 13)",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,8182,"(190, 13)",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,8790,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,NaN,ActionStartTask(action);,Task.Run(() => ActionStartTask(action));,() => ActionStartTask(action)
9,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,None,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,5177,"(127, 13)",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,5501,"(130, 13)",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,6109,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,NaN,await ActivityStartTask(activity);,Task.Run(() => ActivityStartTask(activity));,() => ActivityStartTask(activity)
10,GridProtectionAlliance_gsf,https://github.com/GridProtectionAlliance/gsf/...,https://github.com/GridProtectionAlliance/gsf/...,PIAdapters: Updated PI adapters to operate in ...,PIAdapters: Moved all PI-SDK code to the STA o...,None,3f893ab0c9f494a7c017d1d81ec89d95c9824243,Source/Libraries/Adapters/PIAdapters/PIOutputA...,20690,"(524, 73)",Source/Libraries/Adapters/PIAdapters/PIOutputA...,17737,"(437, 110)",8335962581b65df64d12ab02b663457a074daa2a,Source/Libraries/Adapters/PIAdapters/PIOutputA...,21250,Source/Libraries/Adapters/PIAdapters/PIOutputA...,NaN,NaN,"(string.Format(""Failed to archive OSI-PI point...",\r\n }\r\n ...,Connection connection = connectionPointVa
11,GridProtectionAlliance_gsf,https://github.com/GridProtectionAlliance/gsf/...,https://github.com/GridProtectionAlliance/gsf/...,GSF.Web: Modified AuthenticationHandler to pro...,GSF.Web: Added logout endpoint for application...,None,5ea0dd4cf2052b91f62de9571271c083299201ae,Source/Libraries/GSF.Web/Security/Authenticati...,7183,"(162, 13)",Source/Libraries/GSF.Web/Security/Authenticati...,6693,"(158, 13)",01fa19f073082541954aa85bad297354d6a22912,Source/Libraries/GSF.Web/Security/Authenticati...,8477,Source/Libraries/GSF.Web/Security/Authenticati...,NaN,NaN,return base.ApplyResponseChallengeAsync();,return Task.Run(() =>\n {\n ...,() =>\n {\n Security...
12,openrails_openrails,https://github.com/openrails/openrails/commit/...,https://github.com/openrails/openrails/commit/...,Changes to CheckAnyOf and CheckAllOf.\nAlso pr...,Handles all test cases in Notifications.docx\n,None,bdfcd3eee3373a17e23bcbcd909c1b99aec858b9,Source/Menu/Notifications/NotificationManager.cs,10416,"(255, 17)",Source/Menu/Notifications/NotificationManager.cs,7752,"(186, 13)",6cf527236a219214161a63301a9058a0fc5bc1d9,Source/Menu/Notifications/NotificationManager.cs,8603,Source/Menu/Notifications/NotificationManager.cs,NaN,NaN,"AddItemToPage(page, item);",n.SuffixItemList?.ForEach(item => AddItemToPag...,"item => AddItemToPage(page, item)"
13,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,fix UTF encoded spans that have been split be...,fix sequences of encoded spans in MailMimePars...,None,eb4c02ecc85cf51b4ea75e965aac6606b4b9804d,Signum.Engine.Extensions/Mailing/Pop3/MailMime...,13461,"(343, 39)",Signum.Engine.Extensions/Mailing/Pop3/MailMime...,13751,"(350, 19)",a8c090b190a185ff32318668039c0ed8e16c9e44,Signum.Engine.Extensions/Mailing/Pop3/MailMime...,13773,Signum.Engine.Extensions/Mailing/Pop3/MailMime...,NaN,NaN,"eplace(headers[key].ToString(), @""=\?(?<enc>[^...","var cod = list.Select(m=> m.Groups[""cod""].Va...","t(m=> m.Groups[""cod""].Value.ToUpper("
14,anoyetta_ACT.Hojoring,https://github.com/anoyetta/ACT.Hojoring/commi...,https://github.com/anoyetta/ACT.Hojoring/commi...,FFXIV_MemoryReader 内蔵版への移行についてフォローするようにした,FFXIV_MemoryReader を同梱ではなく完全に内蔵するようにした,None,b8b9180e8da26ae3cf87e89ce55fcf9d2a746c4c,source/FFXIV.Framework/FFXIV.Framework/FFXIVHe...,2476,"(86, 3)",source/FFXIV.Framework/FFXIV.Framework/FFXIVHe...,2874,"(88, 10)",5e2bf7f7463f17d1649e90058716f838da161cd7,source/FFXIV.Framework/FFXIV.Framework/FFXIVHe...,6351,source/FFXIV.Framework/FFXIV.Framework/FFXIVHe...,NaN,NaN,{\r\n ...,message += dll;\r\n\r\n ...,"n was added.\n"" +\r\n ""Plea..."
15,SpiceSharp_SpiceSharp,https://github.com/SpiceSharp/SpiceSharp/commi...,https://github.com/SpiceSharp/SpiceSharp/commi...,Voltage-controlled current source\n,Added AC properties for sources\n,None,c5e637c4b644838ba6f0a329d213a32dca028d3d,SpiceSharp/Components/Currentsources/VCCS/AcBe...,1009,"(32, 13)",SpiceSharp/Components/Currentsources/VCCS/AcBe...,1419,"(43, 28)",59556e52d5656ac3f7e47ad5149b856cbdd162bf,SpiceSharp/Components/Currentsources/VCCS/AcBe...,1401,SpiceSharp/Components/Currentsources/VCCS/AcBe...,NaN,NaN,return new Complex(\n ckt.State...,return () => state.Solution[VCCSposNode] - sta...,(State state) => state.Solution[VCCSposNode] -...
16,microsoft_qsharp-compiler,https://github.com/microsoft/qsharp-compiler/c...,https://github.com/microsoft/qsharp-compiler/c...,Reverts #989 and manually reverts the change f...,Temporarily reverting ref count changes for re...,None,008bc5f0d4c2cbc2607e6ee3f090b08e2f33e1eb,src/QsCompiler/QirGeneration/ScopeManager.cs,31186,"(641, 13)",src/QsCompiler/QirGeneration/ScopeManager.cs,32196,"(640, 13)",28dc3bc67d706d9f9589e738db26331d9ce31e7e,src/QsCompiler/QirGeneration/ScopeManager.cs,32238,src/QsCompiler/QirGeneration/ScopeManager.cs,NaN,NaN,"this.scopes.Peek().RegisterRelease(value, rele...","this.scopes.Peek().RegisterRelease(value, load...",loaded => this.sharedState.CurrentBuilder.Call...
17,kwaazaar_Resonance,https://github.com/kwaazaar/Resonance/commit/f...,https://github.com/kwaazaar/Resonance/commit/5...,Core all async. Other project yet to convert.\n,Added ConfigureAwait(false) to all awaits.\n,None,f9dea8bb12e3cd92f62241b1154658ca33fc5d4e,Resonance.Core/Repo/Database/DbEventingRepo.cs,22364,"(572, 13)",Resonance.Core/Repo/Database/DbEventingRepo.cs,24400,"(601, 13)",5da891bb3b3e1157a8f56e3d2fa3957427ffc23c,Resonance.Core/Repo/Database/DbEventingRepo.cs,24894,Resonance.Core/Repo/Database/DbEventingRepo.cs,NaN,NaN,var headers = topicEvent.Headers != null ? Jso...,var headers = topicEvent.Headers != null ? awa...,() => JsonConvert.SerializeObject(topicEvent.H...
18,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Replaced list.Where(condition).FirstOrDefault(...,"Code changes for Copy paste fixes, Defect no= ...",None,b3901ca01150b9c5e333989eab999d2a71c73af6,Ginger/GingerCore/GeneralLib/General.cs,15951,"(425, 21)",Ginger/GingerCore/GeneralLib/General.cs,15864,"(425, 21)",71c805dce882c1ce7e165b5fedcca33d740f92a7,Ginger/GingerCore/GeneralLib/General.cs,16689,Ginger/GingerCore/GeneralLib/General.cs,NaN,NaN,if ((from x in WorkSpace.Instance.SolutionRepo...,if (WorkSpace.Instance.SolutionRepository.GetA...,x => x.Name == resultValue
19,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,ProcessOperation.Retry & UnsafeUpdate on line ...,ProcessExceptionLineDN\n,None,22ede7e937a8f3e03aa889056a6ec651daf68847,Signum.Engine.Extensions/Processes/ProcessLogi...,19344,"(502, 65)",Signum.Engine.Extensions/Processes/ProcessLogi...,19760,"(510, 57)",9068187eea7385658099d6f815e5d7bcd8d0150f,Signum.Engine.Extensions/Processes/ProcessLogi...,19829,Signum.Engine.Extensions/Processes/ProcessLogi...,NaN,NaN,eNew())\r\n,ion.ForceNew())\r\n {\r...,{\r\n
20,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,"SchemaSynchronizer moved, Interactive=false, a...",Improve sync experience (mainly for Enums)\n\n...,None,07583578f05776147cc4798ff1c23ab73bd1d22f,Signum.Engine/Engine/Synchronizer.cs,5439,"(144, 78)",Signum.Engine/Engine/Synchronizer.cs,7148,"(185, 53)",092562435ff1a9113203549d4b3f630ab2bb7c81,Signum.Engine/Engine/Synchronizer.cs,8227,Signum.Engine/Engine/Synchronizer.cs,NaN,NaN,string>();\r\n\r\n while (oldOnly.C...,t > 0)\r\n {\r\n Sel...,Only.Count > 0 && newOnly.Count > 0)\r\n
21,anoyetta_ACT.Hojoring,https://github.com/anoyetta/ACT.Hojoring/commi...,https://github.com/anoyetta/ACT.Hojoring/commi...,fixed bug,a タグ から aタグ へのgotoが2回目以降動作しなかった不具合を修正した,None,3bd492701dcf6dbe8e73329de05201fcf41d8c08,source/ACT.SpecialSpellTimer/ACT.SpecialSpellT...,65325,"(2052, 21)",source/ACT.SpecialSpellTimer/ACT.SpecialSpellT...,65125,"(2042, 31)",e3d9318b235b14f505824159aa128a3d8ec91594,source/ACT.SpecialSpellTimer/ACT.SpecialSpellT...,65104,source/ACT.SpecialSpellTimer/ACT.SpecialSpellT...,NaN,NaN,continue;\r\n }\r\n\r\n...,ue;\r\n }\r\n\r\n ...,var vnotices = act.VisualN...
22,mchudy_InstantDelivery,https://github.com/mchudy/InstantDelivery/comm...,https://github.com/mchudy/InstantDelivery/comm...,some asyncs everywhere\n,Add checkbox for marking a package as delivere...,None,8bfe406679fe5ee4a904ec98dae9a5bda78117c2,InstantDelivery.ViewModel/ViewModels/PackagesV...,362,"(15, 13)",InstantDelivery.ViewModel/ViewModels/PackagesV...,467,"(18, 13)",5346a27d4917aaa2c9557fb2784d299500bd7556,InstantDelivery.ViewModel/ViewModels/PackagesV...,994,InstantDelivery.ViewModel/ViewModels/PackagesV...,NaN,NaN,service.CalculatePackageCost(Package);,await Task.Run(() =>\n {\n ...,() =>\n {\n service....
23,AvaloniaUI_AvaloniaVS,https://github.com/AvaloniaUI/AvaloniaVS/commi...,https://github.com/AvaloniaUI/AvaloniaVS/commi...,feat: Allow to discover the internal classes a...,fix: Address review\n\nhttps://github.com/Aval...,None,b41b53a2a21bdbfa0bfa1a001565a66300212388,CompletionEngine/Avalonia.Ide.CompletionEngine...,25106,"(555, 13)",CompletionEngine/Avalonia.Ide.CompletionEngine...,26393,"(575, 13)",9453cb4cc3f7657d307d9ce1926f8d9096dd7125,CompletionEngine/Avalonia.Ide.CompletionEngine...,26532,CompletionEngine/Avalonia.Ide.CompletionEngine...,NaN,NaN,"types.TryGetValue(""Avalonia.Controls.Control"",...","types.TryGetValue(key => key.StartsWith(""Avalo...","key => key.StartsWith(""Avalonia.Controls.Contr..."
24,microsoft_qsharp-compiler,https://github.com/microsoft/qsharp-compiler/c...,https://github.com/microsoft/qsharp-compiler/c...,Ref count optimizations and some bug fixes (#9...,Splitting out general purpose helpers for bran...,None,9689a96fe3c77123a96b6ba79319e547623b8180,src/QsCompiler/QirGeneration/Context.cs,69751,"(1279, 13)",src/QsCompiler/QirGeneration/Context.cs,69853,"(1270, 13)",34bd1fe9cf10e1264b46ef6c6c1266c071e495c1,src/QsCompiler/QirGeneration/Context.cs,69914,src/QsCompiler/QirGeneration/Context.cs,NaN,NaN,"this.CreateForLoop(startValue, EvaluateConditi...","this.CreateForLoop(startValue, EvaluateConditi...",loopVar => executeBody(array.GetArrayElement(l...
25,anoyetta_ACT.Hojoring,https://github.com/anoyetta/ACT.Hojoring/commi...,https://github.com/anoyetta/ACT.Hojoring/commi...,モブリストで風脈の泉（オブジェクト）を扱えるようにした,モブリストの判定でcase sensitiveを無効にした,None,8eecc7d64565a55acc700a184c78b0eb0bd1f5f6,source/ACT.UltraScouter/ACT.UltraScouter.Core/...,6957,"(217, 13)",source/ACT.UltraScouter/ACT.UltraScouter.Core/...,6951,"(218, 39)",47ecf2f6d550c8898d04de9ecb7482a5effa8586,source/ACT.UltraScouter/ACT.UltraScouter.Core/...,6786,source/ACT.UltraScouter/ACT.UltraScouter.Core/...,NaN,NaN,x.Type == Actor.Type.TreasureCoffer ||\r\n...,Enumerable<Combatant>);\r\n var act...,\n x != null &&\r\n ...
26,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,(TFS CS 4096)\n\n,(TFS CS 4552)\n\n,None,2f429cedfc8a45053cc6398c790bdf9f230d96eb,Signum.Windows.Extensions/Authorization/Permis...,548,"(21, 3)",Signum.Windows.Extensions/Authorization/Permis...,548,"(21, 3)",e24b32556cd5150c7f6b13f3d6c08fd1d5e9d83e,Signum.Windows.Extensions/Authorization/Permis...,569,Signum.Windows.Extensions/Authorization/Permis...,NaN,NaN,{\r\n return Server.Service<I...,{\r\n return Server.Return((I...,return Server.Return((IPermissionAuthServer s)...
27,GridProtectionAlliance_gsf,https://github.com/GridProtectionAlliance/gsf/...,https://github.com/GridProtectionAlliance/gsf/...,GSF.Collections: Added DoubleBufferedQueueMana...,GSF.Timeseries - Incorporated the new extensib...,None,8fa4fed2b0bb073229e9593355ae5b04a22bb1f8,Source/Libraries/GSF.TimeSeries/Adapters/Routi...,23956,"(567, 23)",Source/Libraries/GSF.TimeSeries/Adapters/Routi...,7415,"(164, 10)",a461dac99e15ecb593e33bfa24184cde5819089b,Source/Libraries/GSF.TimeSeries/Adapters/Routi...,7484,Source/Libraries/GSF.TimeSeries/Adapters/Routi...,NaN,NaN,"eueMeasurementsForProcessing(pair.Key, pai",IOutputAdapter outputAdapter;\r\n\r\n ...,measurements => actionAdapter.QueueMeasurement...
28,cliftonm_HOPE,https://github.com/cliftonm/HOPE/commit/06ceff...,https://github.com/cliftonm/HOPE/commit/1c0399...,Trying a different thread manager.\n,"Rework of image viewer, thumbnail converter, t...",None,06ceff4574d41ed0024195a3b68d286fc9931255,Receptors/ThumbnailCreatorReceptor/ReceptorDef...,1592,"(59, 72)",Receptors/ThumbnailCreatorReceptor/ReceptorDef...,1394,"(57, 67)",1c039971e89b2e6819444402b74f7019bc9107cc,Receptors/ThumbnailCreatorReceptor/ReceptorDef...,1387,Receptors/ThumbnailCreatorReceptor/ReceptorDef...,NaN,NaN,.Width);\r\n\t\t\t\t\timage.Ta,map.Width);\r\n\t\t\timage.Tag = fn;\r\n\t\t\t...,Control)Application.OpenForm
29,duplicati_duplicati,https://github.com/duplicati/duplicati/commit/...,https://github.com/duplicati/duplicati/commit/...,Changed the way the OneDrive authid is passed ...,Updated the OneDrive backend to use the shared...,None,0cf41f8b17c26293b8bdd0b5b0962284d23c5713,Duplicati/Library/Backend/OneDrive/OneDrive.cs,3668,"(100, 63)",Duplicati/Library/Backend/OneDrive/OneDrive.cs,3754,"(103, 60)",4a299c850056ae7dfd77730eec240a64e29de081,Duplicati/Library/Backend/OneDrive/OneDrive.cs,4272,Duplicati/Library/Backend/OneDrive/OneDrive.cs,NaN,NaN,me.UtcNow)\r\n {\r\n ...,eTime.UtcNow)\r\n {\r\n ...,try\r\n {\r\n ...

In [ ]:
df = pd.read_json(
    "/Users/kz/labo/study/fact_replacing_task_re/results/rq4/csharp_shuffle2.json"
)

df

,name_with_owner,insert url,delete url,replacement_msg,delete_msg,coding,insert commit,insert src file,insert src start pos,insert dst file,insert dst start pos,delete commit,delete src file,delete src start pos,delete dst file,delete dst start pos,insert src file content,insert dst file content,delete src file content
0,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,elefantes\n\n(TFS CS 5989)\n,Chequinazo entitygroups\n\n(TFS CS 6663)\n,NaN,fe7d3ff8826e4f2dfae0a3085882f37f3d990d5c,Signum.Engine.Extensions/Authorization/EntityG...,"[113, 7]",Signum.Engine.Extensions/Authorization/EntityG...,"[115, 3]",eb1b533826ad0b786fe883bdabdda8823e246a1b,Signum.Engine.Extensions/Authorization/EntityG...,"[130, 51]",Signum.Engine.Extensions/Authorization/EntityG...,NaN,if (!saveDisabled && args.WasModified)\r...,if (!saveDisabled && ident.Modified)...,aveOptions.Destiny))\r\n {\r\n ...
1,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,NaN,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[98, 13]",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[101, 13]",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[119, 22]",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,BusinessFlowStartTask(businessFlow);,Task.Run(() => BusinessFlowStartTask(businessF...,() => BusinessFlowStartTask(businessFlow)
2,AutoMapper_AutoMapper,https://github.com/AutoMapper/AutoMapper/commi...,https://github.com/AutoMapper/AutoMapper/commi...,Array mapping simplified quite a bit\n,"Instead of using ToArray, which double maps. F...",NaN,d8ea3389e0104fad7787964e369a1973697a0445,src/AutoMapper/Mappers/ArrayMapper.cs,"[46, 11]",src/AutoMapper/Mappers/ArrayMapper.cs,"[29, 13]",fb68f979b31f4875d636d18d0e6f6dbd6c74fc7b,src/AutoMapper/Mappers/ArrayMapper.cs,"[21, 34]",src/AutoMapper/Mappers/ArrayMapper.cs,NaN,return array as TDestinatio,return source.Cast<TSourceElement>()\n ...,"item => newItemFunc(item, itemContext)"
3,Ginger-Automation_Ginger,https://github.com/Ginger-Automation/Ginger/co...,https://github.com/Ginger-Automation/Ginger/co...,Changed async void to task\n,making AccountReport Logger method async\n,NaN,58eaea8958fe9336d1c1be586932b7785c4735dd,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[84, 13]",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[87, 13]",79a02f5bfbdc412bf3872a44306b5d3876b855b3,Ginger/GingerCoreNET/Run/RunListenerLib/Center...,"[105, 22]",Ginger/GingerCoreNET/Run/RunListenerLib/Center...,NaN,RunnerRunEndTask(gingerRunner);,Task.Run(() => RunnerRunEndTask(gingerRunner));,() => RunnerRunEndTask(gingerRunner)
4,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,TryToken and QueryTokenDN builder with error m...,SubTokens(canAggregate)\n,NaN,058f6bf4968cfb578ba5b41f6b1e9bc1b07f5341,Signum.Web.Extensions/Chart/ChartClient.cs,"[220, 68]",Signum.Web.Extensions/Chart/ChartClient.cs,"[199, 92]",9880339ef979a380e89089dacaab00ec86c3c093,Signum.Web.Extensions/Chart/ChartClient.cs,"[199, 2]",Signum.Web.Extensions/Chart/ChartClient.cs,NaN,o(\r\n,"chartToken, IChartBase chart, QueryDescription...",{\r\n bool canAggregate = (c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,signumsoftware_framework,https://github.com/signumsoftware/framework/co...,https://github.com/signumsoftware/framework/co...,(TFS CS 4096)\n\n,.Net Framework 4.0 y Visual Studio 2010\n\n(TF...,NaN,2f429cedfc8a45053cc6398c790bdf9f230d96eb,Signum.Windows.Extensions/Authorization/AuthCl...,"[31, 9]",Signum.Windows.Extensions/Authorization/AuthCl...,"[31, 9]",ce1be332034042b46828ed0e08ab4203b0ea3f01,Signum.Windows.Extensions/Authorization/AuthCl...,"[41, 7]",Signum.Windows.Extensions/Authorization/AuthCl...,NaN,{\r\n propertyRules...,{\r\n propertyRules...,propertyRules = Server.Return((IProp...
321,getsentry_sentry-dotnet,https://github.com/getsentry/sentry-dotnet/com...,https://github.com/getsentry/sentry-dotnet/com...,ref: add scope off of base scope\n,ref: wrap hub\n,NaN,22067c862bcb85fe924b7af7f9c62d738cdb0e9b,src/Sentry.AspNetCore/ApplicationBuilderExtens...,"[44, 21]",src/Sentry.AspNetCore/ApplicationBuilderExtens...,"[44, 21]",33f48da1d4a5d2d87adca9b4ac94cef6d6d8257d,src/Sentry.AspNetCore/ApplicationBuilderExtens...,"[44, 40]",src/Sentry.AspNetCore/ApplicationBuilderExtens...,NaN,o.AddExceptionProcessorProvider(provider.GetSe...,hub.ConfigureScope(s => s.AddExceptionProcesso...,s => s.AddExceptionProcessorProvider(provider....
322,PoESkillTree_PoESkillTree,https://github.com/PoESkillTree/PoESkillTree/c...,https://github.com/PoESkillTree/PoESkillTree/c...,Ask user for BuildSavePath on first start\n\n(...,Build save path can be changed through setting...,NaN,9045f3e7b90f9c1460d6f296a9714f6f3304f3a6,WPFSKillTree/Model/Serialization/PersistentDat...,"[41, 13]",WPFSKillTree/Model/Serialization/PersistentDat...,"[39, 13]",46f1039aaa07c323180c960ecb1b881efcddbf50,WPFSKillTree/Model/Serialization/PersistentDat...,"[39, 33]",WPFSKillTree/Model/Serialization/PersistentDat...,NaN,serializer.SerializeAllBuilds();,data.Initialized += () => serializer.Serialize...,() => serializer.SerializeAllBuilds()
323,FOGProject_fog-client,https://github.com/FOGProject/fog-client/commi...,https://github.com/FOGProject/fog-client/commi...,Update notification gui\n,Use a json in shutdown gui creation\n,NaN,9d061d077a638c4d04a97dc31987f06aa13b6f6a,NotificationGUI/MainForm.cs,"[30, 4]",NotificationGUI/MainForm.cs,"[20, 13]",c30682e3e0399a7b977ada4cca7917aeb6ba2e10,NotificationGUI/MainForm.cs,"[20, 44]",NotificationGUI/MainForm.cs,NaN,foreach(var arg in args) {\n\t\t\t if (arg....,foreach (var arg in args.Where(arg => arg.Cont...,"arg => arg.Contains(""noAbort"")"
324,d60_Cirqus,https://github.com/d60/Cirqus/commit/c7e6cd622...,https://github.com/d60/Cirqus/commit/58d905c9c...,Inheritance support for tests harness\n,"Revert ""Inheritance support for tests harness""...",NaN,c7e6cd6227c3104f5e28b371cd5b113bf17a4158,d60.Cirqus.Testing/CirqusTestsHarness.cs,"[278, 24]",d60.Cirqus.Testing/CirqusTestsHarness.cs,"[71, 45]",58d905c9c916d847873c72ce8a038d125ca63f48,d60.Cirqus.Testing/CirqusTestsHarness.cs,"[71, 73]",d60.Cirqus.Testing/CirqusTestsHarness.cs,NaN,"ew InvalidOperationException(string.Format(""Ca...",T> @event) where T : AggregateRoot\r\n ...,teRoot\r\n {\r\n \r

In [5]:
languages = [
    "java",
    "javascript",
    "cpp",
    "csharp",
    "php",
    "ruby",
]

for language in languages:
    rq4(language)

  0%|          | 0/172 [00:00<?, ?it/s]

  0%|          | 0/183 [00:00<?, ?it/s]

  0%|          | 0/164 [00:00<?, ?it/s]

  0%|          | 0/325 [00:00<?, ?it/s]

  0%|          | 0/18 [00:00<?, ?it/s]

  0%|          | 0/24 [00:00<?, ?it/s]

In [ ]:
def calculate_line_offsets(source_code: str) -> list[int]:
    """
    Calculates the start offsets for each line in the source code.

    Args:
        source_code (str): The full source code as a string.

    Returns:
        list[int]: A list of line start offsets.
    """
    offsets = [0]
    current_offset = 0

    for line in source_code.splitlines(keepends=True):
        current_offset += len(line)
        offsets.append(current_offset)

    return offsets


def position_for(offset: int, source_code: str) -> tuple[int, int]:
    """
    Converts an offset into a (line, column) position based on the source code.

    Args:
        offset (int): The offset in the source code string.
        source_code (str): The full source code as a string.

    Returns:
        tuple: (line, column), both starting from 1.
    """
    lines = calculate_line_offsets(source_code)
    line = bisect.bisect_right(lines, offset) - 1
    column = offset - lines[line] + 1

    return line + 1, column


# サンプルのソースコード文字列
source_code = """public class Sample {


    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}"""


def get_line_column(source: str, offset: int) -> tuple[int, int]:
    lines = source[:offset].splitlines()
    line_number = len(lines)
    column_number = len(lines[-1]) + 1 if lines else 1
    return line_number, column_number


# 使用例
offset = source_code.find("System.out")
print(f"Offset: {offset}")
print("Position:", position_for(offset, source_code))

print(get_line_column(source_code, offset))  # (3, 7)


# サンプルコード
source_code = (
    """def add(a, b):\n\n    return a + b\n# 44tomgrgrgmorvpov\nprint(add(2, 3))"""
)
offset = source_code.index("add(2, 3)")  # "add(2, 3)" の開始位置

print(f"Offset: {offset}")
print("Position:", position_for(offset, source_code))

print(get_line_column(source_code, offset))  # (3, 7)

Offset: 77
Position: (5, 9)
(5, 9)
Offset: 59
Position: (5, 7)
(5, 7)

In [24]:
print(source_code)

def add(a, b):

    return a + b
# 44tomgrgrgmorvpov
print(add(2, 3))

In [ ]:
import os
from retry.api import retry_call
from python.git_operate import get_repo
from tqdm.auto import tqdm

import subprocess

URL_TEMPLATE = "https://github.com/{name_with_owner}/commit/{commit}"

top_dir = os.path.join(os.path.abspath(""))


def removeNonAscii(s):
    return "".join(c for c in s if ord(c) < 128)


language = "java"
os.makedirs(os.path.join(res_dir, f"rq4/{language}"), exist_ok=True)

rq4_df = __RQ4(language)

res_df = pd.DataFrame()

for i, row in tqdm(rq4_df.iterrows(), total=len(rq4_df)):
    name_with_owner = row["name_with_owner"]
    insert_commit = row["insert commit"]
    insert_src_file = row["insert src file"]
    insert_dst_file = row["insert dst file"]
    insert_src_start_pos = row["insert src start pos"]
    insert_src_end_pos = row["insert src end pos"]
    insert_dst_start_pos = row["insert dst start pos"]
    insert_dst_end_pos = row["insert dst end pos"]
    delete_commit = row["delete commit"]
    delete_src_file = row["delete src file"]
    delete_start_pos = row["delete src start pos"]
    delete_end_pos = row["delete src end pos"]
    delete_dst_file = row["delete dst file"]

    assert insert_dst_file == delete_src_file

    repo = get_repo(top_dir, name_with_owner.replace("_", "/", 1), language)

    insert_src_file_content = removeNonAscii(
        retry_call(
            repo.git.show,
            fargs=[f"{insert_commit}^:{insert_src_file}"],
            tries=5,
            delay=1,
        )
    )
    insert_src_file_path = os.path.join(top_dir, f"rq4/java/{i}_insert_src.java")

    insert_dst_file_content = removeNonAscii(
        retry_call(
            repo.git.show,
            fargs=[f"{insert_commit}:{insert_dst_file}"],
            tries=5,
            delay=1,
        )
    )
    insert_dst_file_path = os.path.join(top_dir, f"rq4/java/{i}_insert_dst.java")

    delete_src_file_content = removeNonAscii(
        retry_call(
            repo.git.show,
            fargs=[f"{delete_commit}^:{delete_src_file}"],
            tries=5,
            delay=1,
        )
    )
    delete_src_file_path = os.path.join(top_dir, f"rq4/java/{i}_delete_src.java")

    delete_dst_file_content = removeNonAscii(
        retry_call(
            repo.git.show,
            fargs=[f"{delete_commit}:{delete_dst_file}"],
            tries=5,
            delay=1,
        )
    )
    delete_dst_file_path = os.path.join(top_dir, f"rq4/java/{i}_delete_dst.java")

    with open(insert_src_file_path, "w") as f:
        f.write(insert_src_file_content)
    with open(insert_dst_file_path, "w") as f:
        f.write(insert_dst_file_content)
    with open(delete_src_file_path, "w") as f:
        f.write(delete_src_file_content)
    with open(delete_dst_file_path, "w") as f:
        f.write(delete_dst_file_content)

    process1 = subprocess.Popen(
        f"gumtree webdiff -g java-treesitter-ng --port 4567 {insert_src_file_path} {insert_dst_file_path}",
        shell=True,
        text=True,
    )
    process2 = subprocess.Popen(
        f"gumtree webdiff -g java-treesitter-ng --port 4568 {delete_src_file_path} {delete_dst_file_path}",
        shell=True,
        text=True,
    )

    print(
        URL_TEMPLATE.format(
            name_with_owner=name_with_owner.replace("_", "/", 1), commit=delete_commit
        )
    )

    process1.wait()
    process2.wait()

    break

  0%|          | 0/172 [00:00<?, ?it/s]

https://github.com/1and1/Troilus/commit/9c2a67349b9aba6da132587270f9603e2e5408b8

In [ ]:
import bisect


def calculate_line_offsets(source_code):
    """
    Calculates the start offsets for each line in the source code.

    Args:
        source_code (str): The full source code as a string.

    Returns:
        list[int]: A list of line start offsets.
    """
    offsets = [0]
    current_offset = 0

    for line in source_code.splitlines(keepends=True):
        current_offset += len(line)
        offsets.append(current_offset)

    return offsets


def position_for(offset, source_code):
    """
    Converts an offset into a (line, column) position based on the source code.

    Args:
        offset (int): The offset in the source code string.
        source_code (str): The full source code as a string.

    Returns:
        tuple: (line, column), both starting from 1.
    """
    lines = calculate_line_offsets(source_code)
    line = bisect.bisect_right(lines, offset) - 1
    column = offset - lines[line] + 1

    return line + 1, column


# サンプルのソースコード文字列
source_code = """public class Sample {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}"""

# 使用例
offset = 22
print(calculate_line_offsets(source_code))
print(f"Offset: {offset}")
print("Position:", position_for(offset, source_code))

[0, 22, 67, 112, 118, 119]
Offset: 22
Position: (2, 1)

In [13]:
source_code[21]

'\n'

In [10]:
for i, line in enumerate(source_code.splitlines(keepends=True)):
    print(i, line)

0 public class Sample {

1     public static void main(String[] args) {

2         System.out.println("Hello, World!");

3     }

4 }

In [ ]:
/Users/kz/labo/study/fact_replacing_task_re/.venv/bin/python /Users/kz/labo/study/fact_replacing_task_re/rq4.py java -s 24