In [2]:
import sys
import os


import pandas as pd

sys.path.append(os.path.join(os.path.abspath(""), "../src/python"))

from config import (
    LANGUAGES,
    RESULT_DIR,
)

In [5]:
res = {}

for lang in LANGUAGES:
    df = pd.read_csv(RESULT_DIR / "rq4" / f"{lang}.csv")
    df.dropna(inplace=True)
    res[lang] = df["consultation"].value_counts()

df_count = pd.DataFrame(res).fillna(0).astype(int).T

df_count = df_count[["差し戻し", "機能変更", "機能削除", "誤検出", "調査不能"]]

df_count

consultation  差し戻し  機能変更  機能削除  誤検出  調査不能
java            12    36     2    9     0
javascript      31    10     9   12     1
ruby             2    21     1    0     0
php              2    10     3    3     0
csharp           9    37     5    7     0
cpp              6    36     8   67     0

In [7]:
df_count = df_count.drop("調査不能", axis=1)
df_count = df_count.drop("誤検出", axis=1)

df_count

consultation  差し戻し  機能変更  機能削除
java            12    36     2
javascript      31    10     9
ruby             2    21     1
php              2    10     3
csharp           9    37     5
cpp              6    36     8

In [ ]:
df_ratio = (
    df_count.div(df_count.sum(axis=1), axis=0)
    .round(2)
    .sort_values("差し戻し", ascending=False)
)

df_ratio

consultation  差し戻し  機能変更  機能削除
javascript    0.62  0.20  0.18
java          0.24  0.72  0.04
csharp        0.18  0.73  0.10
php           0.13  0.67  0.20
cpp           0.12  0.72  0.16
ruby          0.08  0.88  0.04

In [9]:
df_ratio.to_latex(RESULT_DIR / "rq4" / "rq4.tex")